[pytest]
testpaths = tests/cli/lib tests/unit
python_files = test_*.py
python_classes = Test
addopts = --cov=cli.lib --cov-report=term-missing --cov-fail-under=45
filterwarnings =
    ignore::pytest.PytestCollectionWarning
