/**
 * Auto-generated by ll-qa-e2e-spec-to-tests
 * case_id: e2e_case.onboarding.create-plan.main
 * coverage_id: e2e.onboarding.create-plan.main
 */
import { test, expect } from '@playwright/test';
import * as fs from 'fs';

test('e2e_case.onboarding.create-plan.main', async ({ page }) => {
  const runId = `run-${Date.now()}-${process.pid}`;
  const evidenceDir = 'ssot/tests/.artifacts/evidence/e2e';
  const coverageId = 'e2e.onboarding.create-plan.main';
  const caseId = 'e2e_case.onboarding.create-plan.main';

  // Console error collection (anti_false_pass_checks: no_console_errors)
  const consoleErrors: string[] = [];
  page.on('console', msg => {
    if (msg.type() === 'error') consoleErrors.push(msg.text());
  });

  // Network response collection
  const networkResponses: { method: string; url: string; status: number }[] = [];
  page.on('response', response => {
    networkResponses.push({
      method: response.request().method(),
      url: response.url(),
      status: response.status()
    });
  });

  try {
    // === Setup: Navigate to entry_point ===
    await page.goto('http://localhost:3000/login');

    // === User Step 1: fill #username with "testuser" ===
    await page.locator('#username').fill('testuser');
    // expected_result: "username field populated"
    await expect(page.locator('#username')).toHaveValue('testuser');

    // === User Step 2: click #login-btn ===
    await page.locator('#login-btn').click();
    // expected_result: "navigate to dashboard"
    await page.waitForURL(/\/dashboard/);

    // === Assert expected_ui_states ===
    await expect(page.locator('h1')).toHaveText('Dashboard');
    await expect(page.locator('h1')).toBeVisible();

    // === Assert expected_persistence: reload_page_keeps_dashboard_state ===
    const persistenceResults: { check: string; expected: string; result: string }[] = [];
    await page.reload();
    const h1AfterReload = page.locator('h1');
    const h1Visible = await h1AfterReload.isVisible();
    const h1Text = await h1AfterReload.textContent();
    persistenceResults.push({
      check: 'reload_page_keeps_dashboard_state',
      expected: 'dashboard still visible after reload',
      result: (h1Visible && h1Text?.trim() === 'Dashboard') ? 'pass' : 'fail'
    });

    // === Evidence collection ===
    fs.mkdirSync(`${evidenceDir}/${runId}`, { recursive: true });

    // Screenshot
    const screenshotPath = `${evidenceDir}/${runId}/screenshot_final.png`;
    await page.screenshot({ path: screenshotPath, fullPage: true });

    // DOM assertions
    const h1TextAssert = await page.locator('h1').textContent();
    const domAssertions = [
      { selector: 'h1', expected: 'Dashboard', actual: h1TextAssert, result: h1TextAssert?.trim() === 'Dashboard' ? 'pass' : 'fail' }
    ];

    // Console error check (anti_false_pass_checks: no_console_errors)
    const consoleErrorsList = consoleErrors.filter(e => !e.includes('favicon'));

    // Write evidence YAML for every item in spec.evidence_required
    // spec requires: screenshot_final, dom_assertions, console_errors
    const evidenceRecord = {
      evidence_record: {
        case_id: caseId,
        coverage_id: coverageId,
        executed_at: new Date().toISOString(),
        run_id: runId,
        evidence: {
          screenshot_final: screenshotPath,
          dom_assertions: domAssertions,
          console_errors: consoleErrorsList
        },
        execution_status: 'success'
      }
    };

    const yamlContent = JSON.stringify(evidenceRecord, null, 2);
    fs.writeFileSync(
      `${evidenceDir}/${runId}/${coverageId}.evidence.yaml`,
      yamlContent,
      'utf-8'
    );

  } catch (error) {
    // Write failure evidence
    const evidenceDirFail = 'ssot/tests/.artifacts/evidence/e2e';
    fs.mkdirSync(`${evidenceDirFail}/${runId}`, { recursive: true });

    let failScreenshotPath = `${evidenceDirFail}/${runId}/error_screenshot.png`;
    try {
      failScreenshotPath = `${evidenceDirFail}/${runId}/error_screenshot.png`;
      await page.screenshot({ path: failScreenshotPath, fullPage: true });
    } catch {
      // screenshot may fail if page is not available
    }

    const errorEvidence = {
      evidence_record: {
        case_id: caseId,
        coverage_id: coverageId,
        executed_at: new Date().toISOString(),
        run_id: runId,
        evidence: {
          error_message: (error as Error).message,
          screenshot_final: failScreenshotPath,
          console_errors: consoleErrors
        },
        execution_status: 'error'
      }
    };

    fs.writeFileSync(
      `${evidenceDirFail}/${runId}/${coverageId}.evidence.yaml`,
      JSON.stringify(errorEvidence, null, 2),
      'utf-8'
    );

    throw error;
  }
});
